Update turtlecoin-nodes.json
turtlecoin/turtlecoin-nodes-json pull request #249
Opened 2021-06-10 17:05 UTC by nodetrtlespain

{
      "name": "Node Turtle Spain",
      "url": "nodeturtlecoinspain.ddns.net",
      "port": 5000,
      "ssl": false,
      "cache": false
    },

2021-06-10 17:08 UTC, brandonlehmann commented
Node is not responding to public requests.

2021-06-13 12:24 UTC, brandonlehmann requested changes
One node is passing (EU) the other is not (Spain)

2021-06-13 12:27 UTC, brandonlehmann commented
If you allowed maintainers to make edits to your PR then I could get one of these to pass through.

2021-06-13 12:29 UTC, nodetrtlespain commented on turtlecoin-nodes.json
> +      "name": "Turtle Node Spain",
{
      
      
              "name": "Turtle Node EU",
      
      
              "url": "nodeturtlecoineu.ddns.net",
      
      
              "port": 5000,
      
      
              "ssl": false,
      
      
              "cache": false
      
      
            },

2021-06-13 12:30 UTC, brandonlehmann commented on turtlecoin-nodes.json
> +      "name": "Turtle Node Spain",
The changes show BOTH nodes still in there. Pick one and remove the other.

2021-06-13 12:42 UTC, closed without merging